### ISSUE TITLE
500-error when starting a provider run

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#124]
# Bug

![afbeelding](https://user-images.githubusercontent.com/37145898/56116549-65c19880-5f66-11e9-94f8-9344eb468aeb.png)

![afbeelding](https://user-images.githubusercontent.com/37145898/56116612-8f7abf80-5f66-11e9-8860-be3fe408f42c.png)

**Comment by alextreme** [comment]
@AlviseSembenico  this was due to the fact that Henri had created a ZGW test scenario, however selected 'no auth' as authentication mechanism. With 'jwt' it works as expected again and Henri can continue.

Feel free to investigate and solve this on vng-test, however due to the API lab updates to vng-staging should be postponed.

**Comment by AlviseSembenico** [comment]
Fix in this PR
https://github.com/VNG-Realisatie/api-testvoorziening/pull/125

**Comment by alextreme** [comment]
Deployed to staging and verified. I've added the 'MOR demo (no auth)' test scenario and this again works as expected.
