### ISSUE TITLE
Error report has corrupt layout

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#185]
# Bug

![afbeelding](https://user-images.githubusercontent.com/37145898/58049698-c3d93100-7b4d-11e9-984c-07519c5c8f9e.png)

**Comment by alextreme** [comment]
@AlviseSembenico I'm not 100% sure what Henri means, but feel free to investigate

**Comment by HenriKorver** [comment]
In the succes report the results are properly aligned to the right

![afbeelding](https://user-images.githubusercontent.com/37145898/58099127-51af2d80-7bdb-11e9-8e8d-621f808cf5f3.png)

**Comment by AlviseSembenico** [comment]
The problem was because of the different length of the sub url.
The problem has been fixed:
![image](https://user-images.githubusercontent.com/28757412/58697310-a734c880-8399-11e9-8575-37255470fd35.png)
![image](https://user-images.githubusercontent.com/28757412/58697345-b156c700-8399-11e9-87a6-db31376c0000.png)
