### ISSUE TITLE
Als leverancier wil ik een banner of badge kunnen publiceren die linkt naar een testrapport op de testvoorziening voor de provider

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#72]
zodat ik aan de buitenwereld kan laten zien in hoeverre mijn API compliant is aan de standaard.

**Toelichting**:

**Oplossingsrichting**:
Zorgen dat testrapporten beschikbaar worden gemaakt door middel van permanente links.

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/3 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by alextreme** [comment]
https://shields.io/

**Comment by alextreme** [comment]
The idea here is to have the test platform to optionally perform a provider test-run on a daily basis. The user can select if this is required or not.

The user of the test platform then has the ability based on a test-run to share a badge/shield of the test-run. 

Based on the latest run the shield can either show a passing, a running or a failing test status.

The link would redirect the visitor to the most recent test report and show how it went during the last run

**Comment by alextreme** [comment]
Colors we still need for the badges:

- Orange -> 'partially succeeded'. This is the situation with Henri's remark on 'gedeeltelijk successvol' (partially succeeded)
- Grijs -> 'not yet run'. Currently the badge is red when the server run has not even been performed. We'd expect that in this case the badge would still be gray.

Further wishes:
- The ability to click through on a badge. This would send the visitor to the server-run detail view, which can be accessible without having to log in. The server-run detail view URL needs to be with a UUID instead of a regular ID. This to ensure the user can not increment/decrement to a different server-run
- Currently the status of the scheduled server-run is 'running'. I'd prefer to show this as 'scheduled'.
- Currently the last run date/time is not shown, so I'm not sure when the server-run was last performed. I'd expect to see a 'Last run' date/time on the server-run detail view.
- Currently when performing an action the user is redirected back to the regular overview of the Test provider. I'd expect the user to be redirected to the 'scheduled' tab of this view. This should also be the case if I've created a scheduled server-run
- I currently don't see when the next time is that the scheduled server-run will be performed. I'd expect this information to be shown on the server-run detail view
- I'd expect a notification-email to be sent to my configured e-mailadres if a scheduled run has failed, with at least a link to the server-run detail view.
- I'd expect the actions 'stop' and 'uitvoeren' to also be possible from the server-run detail view.

**Comment by AlviseSembenico** [comment]
@alextreme  The schedule is the same for every server-run, namely at midnight. Is it still a useful info to display? Or maybe to display in the server list page since it is share by all the server run?

**Comment by alextreme** [comment]
@AlviseSembenico then I'd simply display the next midnight for all scheduled (non-stopped) server runs. This would indeed also be useful for on the server list page (the date it was created is less relevant imho)

**Comment by AlviseSembenico** [comment]
The problem with the fact of the user be redirected to the detail after the creation is that it cannot monitor the status of the test since the status bar is in the list page

**Comment by alextreme** [comment]
@AlviseSembenico feel free to add the status bar / badge to the detail page too

**Comment by HenriKorver** [comment]
> Sliced to only the Provider tests, the badges for the consumer tests (incl 'orange' badge) are out-of-scope for now (@HenriKorver will think how this would work in a new user story).

Done: #158

**Comment by HenriKorver** [comment]
> Can be reviewed after processing the demo-feedback and exposing of the badges for the one-time provider runs.

Indeed, it is important that badges can also be provided for provider-runs that are not scheduled (one-time run)

**Comment by alextreme** [comment]
One-time provider runs now also have badges. Feel free to review
